parameters:
   results_per_page: 10
   www_root: web
   upload_dir: upload
   cache_location: '/../../../var/cache'
   translation_config:
      entities:
          Article:
              heading: text
              content: ckeditor
      display_names:
          article: 'Článok'

services:
    app.service.user:
        class: AppBundle\Service\UserService
        arguments: ['@doctrine.orm.default_entity_manager', '@security.encoder_factory']
    app.service.article:
        class: AppBundle\Service\ArticleService
        arguments: ['@doctrine.orm.default_entity_manager']
    app.service.menu:
        class: AppBundle\Service\MenuService
        arguments: ['@doctrine.orm.default_entity_manager']
    app.service.slug:
        class: AppBundle\Service\SlugService
        arguments: ['@doctrine.orm.default_entity_manager']
    app.service.filter:
        class: AppBundle\Service\FilterService
        arguments: ['@doctrine.orm.default_entity_manager']
    app.service.language:
        class: AppBundle\Service\LanguageService
        arguments: ['@doctrine.orm.default_entity_manager']
    app.service.image:
        class: AppBundle\Service\ImageService
        arguments: ['@doctrine.orm.default_entity_manager', '%www_root%', '%upload_dir%']
    app.service.staticpage:
        class: AppBundle\Service\StaticPageService
        arguments: ['@doctrine.orm.default_entity_manager']
    app.service.cache:
        class: AppBundle\Service\CacheService
        arguments: ['%cache_location%']
    app.twig.template_helper:
        class: AppBundle\Twig\TemplateHelperExtension
        public: false
        arguments: ['@translator.default', '@doctrine.orm.default_entity_manager']
        tags:
            - { name: twig.extension }
    app.service.translation:
        class: AppBundle\Service\TranslationService
        arguments: ['@doctrine.orm.default_entity_manager', '@app.service.cache', '%translation_config%']
