parameters:
   results_per_page: 10
   upload_dir: "upload"
   cache_location: "/../../../var/cache"
   translation_config:
      entities:
          Article:
              heading: "text"
              content: "ckeditor"
      display_names:
          Article: "Článok"
          content: "Obsah"
          heading: "Nadpis"

services:
    app.service.user:
        class: AppBundle\Service\UserService
        arguments: ['@doctrine.orm.default_entity_manager', '@security.encoder_factory']
    app.service.contact:
        class: AppBundle\Service\ContactService
        arguments: ['@doctrine.orm.default_entity_manager', '%mailer_address%', '@swiftmailer.mailer', '@twig']
    app.service.article:
        class: AppBundle\Service\ArticleService
        arguments: ['@doctrine.orm.default_entity_manager']
    app.service.menu:
        class: AppBundle\Service\MenuService
        arguments: ['@doctrine.orm.default_entity_manager']
    app.service.slug:
        class: AppBundle\Service\SlugService
        arguments: ['@doctrine.orm.default_entity_manager', '@app.service.language']
    app.service.filter:
        class: AppBundle\Service\FilterService
        arguments: ['@doctrine.orm.default_entity_manager']
    app.service.language:
        class: AppBundle\Service\LanguageService
        arguments: ['@doctrine.orm.default_entity_manager', '%locale%']
    app.service.image:
        class: AppBundle\Service\ImageService
        arguments: ['@doctrine.orm.default_entity_manager', '%www_root%', '%upload_dir%']
    app.service.staticpage:
        class: AppBundle\Service\StaticPageService
        arguments: ['@doctrine.orm.default_entity_manager']
    app.service.cache:
        class: AppBundle\Service\CacheService
        arguments: ['%cache_location%']
    app.twig.template_helper:
        class: AppBundle\Twig\TemplateHelperExtension
        public: false
        arguments: ['@translator.default', '@doctrine.orm.default_entity_manager']
        tags:
            - { name: twig.extension }
    app.twig.menu_helper:
        class: AppBundle\Twig\MenuHelperExtension
        public: false
        arguments: ['@doctrine.orm.default_entity_manager']
        tags:
            - { name: twig.extension }
    app.twig.image_helper:
        class: AppBundle\Twig\ImageHelperExtension
        public: false
        arguments: ['@doctrine.orm.default_entity_manager']
        tags:
            - { name: twig.extension }
    app.twig.slug:
        class: AppBundle\Twig\SlugExtension
        arguments: ['@app.service.slug', '@app.service.language']
        tags:
            - { name: twig.extension }
    app.helper.dql:
        class: AppBundle\Helper\DqlHelper
    app.service.translation:
        class: AppBundle\Service\TranslationService
        arguments: ['@doctrine.orm.default_entity_manager', '@app.service.language', '@app.service.cache', '@app.helper.dql', '%translation_config%']
