# TODO: Remove unused parameters.
# parameters:
   # results_per_page: 20

services:
    service.article:
        class: AppBundle\Service\ArticleService
        arguments: ['@doctrine.orm.default_entity_manager']
    service.menu:
        class: AppBundle\Service\MenuService
        arguments: ['@doctrine.orm.default_entity_manager']
