# TODO: Remove unused parameters.
parameters:
   results_per_page: 1

services:
    app.service.article:
        class: AppBundle\Service\ArticleService
        arguments: ['@doctrine.orm.default_entity_manager']
    app.service.menu:
        class: AppBundle\Service\MenuService
        arguments: ['@doctrine.orm.default_entity_manager']
    app.service.filter:
        class: AppBundle\Service\FilterService
        arguments: ['@doctrine.orm.default_entity_manager']
    app.twig.template_helper:
        class: AppBundle\Twig\TemplateHelperExtension
        public: false
        arguments: ['@translator.default']
        tags:
            - { name: twig.extension }